### ISSUE TITLE
Schema is not valid! Error

### ISSUE THREAD

**Issue by jeroenpol** [Urigo/WhatsApp-Clone-Server#1071]
I'm almost done with this tutorial but I can't seem to run the server in the final step of the tutorial. When I run `yarn start` I get the following error:

```
(node:21322) UnhandledPromiseRejectionWarning: Error: 
      GraphQL-Modules Error: Schema is not valid!
      - #Module #User doesn't have a valid schema!
      -- "Date" defined in resolvers, but not in schema

      Possible solutions:
      - Check syntax errors in typeDefs
      - Make sure you import correct dependencies
    
    at GraphQLModule.get schema [as schema] (/Users/jeroenpol/Projects/Whatsapp-Clone-Server/node_modules/@graphql-modules/core/src/graphql-module.ts:381:17)
    at selfImports.map.module (/Users/jeroenpol/Projects/Whatsapp-Clone-Server/node_modules/@graphql-modules/core/src/graphql-module.ts:347:63)
    at Array.map (<anonymous>)
    at GraphQLModule.get schema [as schema] (/Users/jeroenpol/Projects/Whatsapp-Clone-Server/node_modules/@graphql-modules/core/src/graphql-module.ts:347:42)
    at selfImports.map.module (/Users/jeroenpol/Projects/Whatsapp-Clone-Server/node_modules/@graphql-modules/core/src/graphql-module.ts:347:63)
    at Array.map (<anonymous>)
    at GraphQLModule.get schema [as schema] (/Users/jeroenpol/Projects/Whatsapp-Clone-Server/node_modules/@graphql-modules/core/src/graphql-module.ts:347:42)
    at Object.<anonymous> (/Users/jeroenpol/Projects/Whatsapp-Clone-Server/index.ts:24:17)
    at step (/Users/jeroenpol/Projects/Whatsapp-Clone-Server/index.ts:32:23)
    at Object.next (/Users/jeroenpol/Projects/Whatsapp-Clone-Server/index.ts:13:53)
(node:21322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21322) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I cannot seem to find the problem, the schemas look alright. I've pushed my code to a Git repo which can be found [here](https://github.com/jeroenpol/Whatsapp-Tutorial-Angular).

Thanks in advance!

**Comment by jeroenpol** [comment]
Fixed it by changing the resolver.ts to:

```
import { GraphQLDateTime, GraphQLDate } from 'graphql-iso-date';
import { IResolvers } from '../../../types';

export default {
  Date: GraphQLDate,
} as any as IResolvers;
```

And the schema to:

```
scalar Date
```

**Comment by Urigo** [comment]
@jeroenpol I've just pushed a new version of the server, might be a good time to go through all the notes as I'm working on this now
