### ISSUE TITLE
[Solved] Can’t start server (role "test" does not exist)

### ISSUE THREAD

**Issue by TechStacker** [Urigo/WhatsApp-Clone-Server#73]
I get this when running `yarn start` 

````
David:WhatsApp-Clone-server david$ yarn dev
yarn run v1.13.0
$ concurrently "yarn generate:watch" "yarn start:server:watch"
$ nodemon --exec yarn start:server -e ts
$ nodemon --exec yarn generate -e graphql
[0] [nodemon] 1.18.10
[1] [nodemon] 1.18.10
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: *.*
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[1] [nodemon] starting `yarn start:server`
[0] [nodemon] starting `yarn generate`
$ ts-node index.ts
$ gql-gen
[0] [10:22:37] Parse configuration [started]
[0] [10:22:37] Parse configuration [completed]
[0] [10:22:37] Generate outputs [started]
[0] [10:22:37] Generate ./types.d.ts [started]
[0] [10:22:37] Load GraphQL schemas [started]
[0] [10:22:39] Load GraphQL schemas [completed]
[0] [10:22:39] Load GraphQL documents [started]
[0] [10:22:39] Load GraphQL documents [completed]
[0] [10:22:39] Generate [started]
[0] [10:22:40] Generate [completed]
[0] [10:22:40] Generate ./types.d.ts [completed]
[0] [10:22:40] Generate outputs [completed]
[1] [nodemon] restarting due to changes...
[0] [nodemon] clean exit - waiting for changes before restart
[1] [nodemon] starting `yarn start:server`
$ ts-node index.ts

[1] (node:30798) UnhandledPromiseRejectionWarning: error: role "test" does not exist
[1]     at Connection.parseE (/Users/david/Dev/WhatsApp-Clone-server/node_modules/pg/lib/connection.js:555:11)
[1]     at Connection.parseMessage (/Users/david/Dev/WhatsApp-Clone-server/node_modules/pg/lib/connection.js:380:19)
[1]     at Socket.<anonymous> (/Users/david/Dev/WhatsApp-Clone-server/node_modules/pg/lib/connection.js:120:22)
[1]     at Socket.emit (events.js:182:13)
[1]     at Socket.EventEmitter.emit (domain.js:442:20)
[1]     at addChunk (_stream_readable.js:283:12)
[1]     at readableAddChunk (_stream_readable.js:264:11)
[1]     at Socket.Readable.push (_stream_readable.js:219:10)
[1]     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[1] (node:30798) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:30798) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] [nodemon] clean exit - waiting for changes before restart

````
I think it's related to Postgres, but I can't find any helpful info when searching for these erros. I have installed Postgres with Homebrew on a MacOS running Sierra. Am I supposed to do more than just installing Pg? 

Also installation instructions for this repo be a bit more clear: 

> Run yarn $ yarn install Run codegen to generate TypeScript types $ yarn generate Run start $ yarn start Note that the server is using a common Cloudinary storage for uploading images. To change Cloudinary URL, please edit the .env file.

Would appreciate some pointers :)

**Comment by TechStacker** [comment]
Ok so the issue was that I needed to do 3 things: 

Create a database called: `whatsapp`
A user called `test`
A password called: `test`

It would be a good idea to add this to the tutorial: 

### Start Postgres command line tool
```
psql postgres
```

### Create database called “test”
```
create database test;
```

### Create User and Password called “test”
```
create user test with login password 'test';
```

Then the Whatsapp server should start up fine.

**Comment by vivekjaiswal** [comment]
getting error. Please advise

Error: Unable to load resolver file: D:/Project/chat/WhatsApp-Clone-server/modules/user/resolvers/resolvers.ts, error: TSError: ⨯ Unable to compile TypeScript:
modules/user/resolvers/resolvers.ts(8,16): error TS2352: Conversion of type '{ Query: { me: (_: {}, __: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => User; users: (obj: {}, args: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => Promise<User[]>; }; Mutation: { updateUser: (obj: {}, { name, picture }: UpdateUserArgs, { injector }: ModuleContext<...>) => Promise<...>;...' to type 'IResolvers<ModuleContext<{ [key: string]: any; }>>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '{ Query: { me: (_: {}, __: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => User; users: (obj: {}, args: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => Promise<User[]>; }; Mutation: { updateUser: (obj: {}, { name, picture }: UpdateUserArgs, { injector }: ModuleContext<...>) => Promise<...>;...' is not comparable to type '{ [typeName: string]: never; }'.
    Property 'Query' is incompatible with index signature.
      Type '{ me: (_: {}, __: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => User; users: (obj: {}, args: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => Promise<User[]>; }' is not comparable to type 'never'.

    at relevantPaths.map.path (D:\Project\chat\WhatsApp-Clone-server\node_modules\@graphql-modules\sonar\src\file-scanner.ts:106:13)
    at Array.map (<anonymous>)
    at Object.loadResolversFiles (D:\Project\chat\WhatsApp-Clone-server\node_modules\@graphql-modules\sonar\src\file-scanner.ts:100:24)
    at Object.<anonymous> (D:\Project\chat\WhatsApp-Clone-server\modules\user\index.js:27:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)

**Comment by agustif** [comment]
> getting error. Please advise
> 
> Error: Unable to load resolver file: D:/Project/chat/WhatsApp-Clone-server/modules/user/resolvers/resolvers.ts, error: TSError: ⨯ Unable to compile TypeScript:
> modules/user/resolvers/resolvers.ts(8,16): error TS2352: Conversion of type '{ Query: { me: (_: {}, __: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => User; users: (obj: {}, args: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => Promise<User[]>; }; Mutation: { updateUser: (obj: {}, { name, picture }: UpdateUserArgs, { injector }: ModuleContext<...>) => Promise<...>;...' to type 'IResolvers<ModuleContext<{ [key: string]: any; }>>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first. Type '{ Query: { me: (_: {}, __: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => User; users: (obj: {}, args: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => Promise<User[]>; }; Mutation: { updateUser: (obj: {}, { name, picture }: UpdateUserArgs, { injector }: ModuleContext<...>) => Promise<...>;...' is not comparable to type '{ [typeName: string]: never; }'.
> Property 'Query' is incompatible with index signature.
> Type '{ me: (_: {}, __: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => User; users: (obj: {}, args: {}, { injector }: ModuleContext<{ [key: string]: any; }>) => Promise<User[]>; }' is not comparable to type 'never'.
> 
> ```
> at relevantPaths.map.path (D:\Project\chat\WhatsApp-Clone-server\node_modules\@graphql-modules\sonar\src\file-scanner.ts:106:13)
> at Array.map (<anonymous>)
> at Object.loadResolversFiles (D:\Project\chat\WhatsApp-Clone-server\node_modules\@graphql-modules\sonar\src\file-scanner.ts:100:24)
> at Object.<anonymous> (D:\Project\chat\WhatsApp-Clone-server\modules\user\index.js:27:24)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> ```

Hey, I just pushed a PR #130  which fixes some similar compilation errors I was getting, maybe you can use my repo to try if that fixes it for you too as it does for me.
https://github.com/agustif/WhatsApp-Clone-server

**Comment by Urigo** [comment]
Hi everyone and thank you for the feedback.

I've just updated the README to include full instructions of how to run a fresh clone.
It is also referencing the new instructions in the tutorial of how to setup your local PostgreSQL database.

We've also added fixed regarding the types.

Please let me know if the new version doesn't work for you for some reason.

Thank you!

**Comment by veerjainATgmail** [comment]
README updates required...

1. PostGres commands to seed the test user. 
user: 'testuser',
password: 'testpassword',
database: 'whatsapp',
>> psql  postgres
>> create database whatsapp
>> create user testuser with encrypted password 'testpassword'

2. the folder name is case sensitive, WhatsApp-Clone-Server with 'A' in whatsapp and 'S' in server

**Comment by Urigo** [comment]
thank you @veerjainATgmail , just added this to the README now!
